from .transformer_wan import WanTransformer3DModel
from .transformer_wan_refextractor import WanTransformer3DModel as WanTransformer3DModel_Refextractor
from .transformer_wan_controlnet import WanTransformer3DModel as WanTransformer3DModel_Controlnet
# from .transformer_wan_refextractor_pose import WanTransformer3DModel as WanTransformer3DModel_Refextractor_Pose
from .transformer_wan_refextractor_2d import WanTransformer3DModel as WanTransformer3DModel_Refextractor_2D
from .transformer_wan_refextractor_2d_split_q import WanTransformer3DModel as WanTransformer3DModel_Refextractor_2D_Q
from .transformer_wan_refextractor_2d_split_q_pose import WanTransformer3DModel as WanTransformer3DModel_Refextractor_2D_Q_Pose
from .transformer_wan_refextractor_2d_pose import WanTransformer3DModel as WanTransformer3DModel_Refextractor_2D_Pose
from .transformer_wan_refextractor_2d_pose_last import WanTransformer3DModel as WanTransformer3DModel_Refextractor_2D_Pose_Final
from .transformer_wan_pose import WanTransformer3DModel as WanTransformer3DModel_Pose
from .transformer_wan_refextractor_2d_controlnet_last_prefix import WanTransformer3DModel as WanTransformer3DModel_Refextractor_2D_Controlnet_prefix
